service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  
functions:
    getUser:
        handler: handler.getUser
        events:
            - http:
                path: getuser
                method: get
                cors: 
                    origins:
                        - ‘*’
    retrieveUsers:
        handler: handler.retrieveUsers
        events:
            - http:
                path: retrieveusers
                method: get
                cors:
                    origins:
                        - ‘*’
    removeUser:
        handler: handler.removeUser
        events:
            - http:
                path: removeuser/{id}
                method: get
                request: 
                    parameters: 
                    paths: 
                        username: true
                